### ISSUE TITLE
Umbrella issue: Switching from Jira to GitHub Issues

### ISSUE THREAD

**Issue by nealrichardson** [apache/arrow#14542]
See [community vote](https://lists.apache.org/thread/nkzbg0481k0dt0l2wq9b2k60kpg5hk62)
See [migration documentation](https://gist.github.com/toddfarmer/12aa88361532d21902818a6044fda4c3)

#### Progress tracking
- [x] Issue migration
  - [x] Decide how to import content (https://github.com/apache/arrow/issues/14513, ...)
  - [x] https://github.com/apache/arrow/issues/14510
  - [x] Labels etc. (see conventions below)
  - [x] Issue links Jira <--> GitHub (https://github.com/apache/arrow/issues/14511, https://github.com/apache/arrow/issues/14520, ...)
  - [x] https://github.com/apache/arrow/issues/14546
  - [x] #14710
  - [x] #14711
  - [x] #14712 
  - [x] #14724
  - [x] #14593
- [x] Establish conventions
  - [x] Component
  - [x] Fix Version
  - [x] Affects Version
  - [x] https://github.com/apache/arrow/issues/14507
- [x] Code updates
  - [x] https://github.com/apache/arrow/issues/14822
  - [x] Release/changelog scripts
  - [x] https://github.com/apache/arrow/issues/14512
  - [ ] TODO comments in code

Relevant JIRAs:

* [x] [[ARROW-18381] MIGRATION: Create milestones for every needed fix version ](https://issues.apache.org/jira/browse/ARROW-18381 "[ARROW-18381] MIGRATION: Create milestones for every needed fix version - ASF JIRA")
* [x] [[ARROW-18380] MIGRATION: Enable bot handling of GitHub issue linked PRs](https://issues.apache.org/jira/browse/ARROW-18380 "[ARROW-18380] MIGRATION: Enable bot handling of GitHub issue linked PRs - ASF JIRA")
* [x] [[ARROW-18378] MIGRATION: Disable issue reporting in ASF Jira](https://issues.apache.org/jira/browse/ARROW-18378 "[ARROW-18378] MIGRATION: Disable issue reporting in ASF Jira - ASF JIRA")
* [x] [[ARROW-18377] MIGRATION: Automate component labels from issue form content](https://issues.apache.org/jira/browse/ARROW-18377 "[ARROW-18377] MIGRATION: Automate component labels from issue form content - ASF JIRA")
* [x] [[ARROW-18376] MIGRATION: Add component labels to GitHub](https://issues.apache.org/jira/browse/ARROW-18376)
* [x] [[ARROW-18375] MIGRATION: Enable GitHub issue type labels](https://issues.apache.org/jira/browse/ARROW-18375 "[ARROW-18375] MIGRATION: Enable GitHub issue type labels - ASF JIRA")

**Comment by raulcd** [comment]
Should we add to the conventions something around severity/priority? I am thinking mainly around how to manage and mark blockers for the Releases.

**Comment by assignUser** [comment]
I think blocker should be a label outside of any other categorization schema. Having additionally at least a distinction between  *bug* and *enhancement* makes sense imho. I don't think anything more granular than that is needed. (+components ofc)

**Comment by assignUser** [comment]
I have searched through INFRA jira to see how other projects handled the transition to issues and have found some relevant tickets:

- https://issues.apache.org/jira/browse/INFRA-23322
- https://issues.apache.org/jira/browse/INFRA-23563
- https://issues.apache.org/jira/browse/INFRA-23386

Take aways: 
- It seems to be possible for the PMC to switch the jira project to read-only, later on it is also possible to hide it from the web (logged in users can still find it though).  
- BEAM developed a migration tool https://github.com/damccorm/jira-to-issues  cc @toddfarmer

**Comment by nealrichardson** [comment]
> > Decide if only migrating open issues
> 
> I think importing all issues regardless of status makes sense as there is no cost to us ( excl. migration script run time) and it has the benefits of keeping all previous discussion and knowledge in one place e.g. for new (and old but they might know to also check jira) contributors to look through prior to opening an issue or for the directional links between issues.

I opened https://github.com/apache/arrow/issues/14546 so we can discuss this further if anyone wants.

**Comment by pitrou** [comment]
* Labels: I think we should review and clean up existing GH labels, which are a bit ad hoc. Any "official" labels should be namespaced so that they can denote multiple categorization schemes without being too much of a mess (for example "Component: C++" rather than simply "C++")

* Component: I would suggest to prefix existing component names with "Component: " and turn them into GH labels

* Fix Version: can apparently be turned into a GH milestone

* Affects Version: this one I find less useful in practice (and it's not consistently filled in), we might simply drop it

* Issue Links: we should at least find a way to migrate the existing ones, as they contain valuable information. One possibility is to append them at the end of the issue description.

**Comment by amol-** [comment]
Things like Affected Version could probably be part of the bug report template instead of being a label. They are helpful information when reproducing issues and thus would be good to have them included in the report, but they have less value in terms of filtering and thus are not very helpful as labels.

Absolutely 👍 on namespacing labels, it's very important to be able to get all possible values of a label in autocomplete.

**Comment by assignUser** [comment]
Some more questions to discuss:
- What should be the new title format? Should we explicitly add the issue|pr number? 
Example from Beam: 
![image](https://user-images.githubusercontent.com/16141871/199527558-1c851c2b-11cf-42f6-871d-f1049f9628ee.png)
- Do we want to keep enforcing "no PR without a linked issue"

**Comment by toddfarmer** [comment]
By way of a quick status update, [this sample issue](https://github.com/toddfarmer/test_import/issues/43) represents the current state of the import mapping work. The migrated content now includes a reference to [this gist](https://gist.github.com/toddfarmer/12aa88361532d21902818a6044fda4c3), a very early draft of migration reference information for the community. Feel free to contribute PRs against that as needed.

**Comment by assignUser** [comment]
One big difference between jira and github is that normal users can only edit the issue body and can not add any meta info unless they are a committer (e.g. assigning it, adding labels...). Some of this can be initially set via issue templates but we might need to think about ways to make issue management available to more people. 

We can add up to[ 20 triage users](https://cwiki.apache.org/confluence/display/INFRA/Git+-+.asf.yaml+features#Git.asf.yamlfeatures-AssigningexternalcollaboratorswiththetriageroleonGitHub) thatt can modify issues but that is pretty restricted.

Another option might be to use bot commands that allow users to update the issues they created with an additional allow list for contributors with more  permissions to extend the 20 traige user slots.

**Comment by pitrou** [comment]
* Issue type: it would be nice if we could keep a distinction between user-visible improvements ("Improvement" or "Feature request") and internal improvements such as refactors ("Task").

**Comment by jorisvandenbossche** [comment]
> One big difference between jira and github is that normal users can only edit the issue body and can not add any meta info unless they are a committer (e.g. assigning it, adding labels...). .. 
> Another option might be to use bot commands that allow users to update the issues they created with an additional allow list for contributors with more permissions to extend the 20 traige user slots.

I would personally wait with starting using bots for this until we notice it might be a problem. On the short term, we can give triage rights to those people that do triage of issues and are not yet committers (at the moment I don't think it would be more than 20?)

**Comment by assignUser** [comment]
A general thought about the migration and our usage of issues going forward:

I think it is important that we copy over relevant information for the existing issues in an appropriate way (otherwise we could just start fresh...) but we also want to avoid falling into the trap that is emulating JIRA 1:1 with issues. This is a new system with different capabilities and ways to do things. 

Finding ever more intricate ways to emulate JIRA will only create unnecessary busy work and make it harder for new contributors to understand the system and why/how it diverges from "normal" GitHub issues.

**Comment by toddfarmer** [comment]
#14648 tracks a problem encountered during a dry run where GitHub rejects importing certain issues with very large comments (possibly also very large descriptions).

**Comment by jorisvandenbossche** [comment]
@toddfarmer going through a few issues from your dry run, some things I noted (some might be known / on purpose):

* Links to pull requests don't yet seem to be included? For example https://github.com/toddfarmer/import_dry_run_3/issues/17912 (https://issues.apache.org/jira/browse/ARROW-18225) has an open PR to address it, but I don't see that mentioned in the issue.  
  That's of course only for the small subset of open JIRAs that have an open PR (for closed ones, the PR is typically linked in the last comment closing the issue)
* Milestone field is not yet populated? 
* It seems the jira2markdown converter cannot handle JIRA markup like ` {{{}code{}}} `. This is not standard usage (one should do `{{code}}`, I suppose you might get this other way with clicking some of buttons in the interface?), but I saw it in a few places (eg the `values[i]` in https://github.com/toddfarmer/import_dry_run_3/issues/18029). Not too important I think, but just noting

**Comment by toddfarmer** [comment]
@jorisvandenbossche:

> Links to pull requests don't yet seem to be included? 
 
This is correct. I've opened #14710 to address this. Please comment there on requirements (e.g., would a comment in the migrated issue suffice? does the PR need to be updated, and if so, how?)

> Milestone field is not yet populated?

Correct - this is pending populating GitHub milestone metadata, which itself has a [few open questions](https://issues.apache.org/jira/browse/ARROW-18381?focusedCommentId=17637500) requiring guidance from the community.

> In some cases, it seems that links are not correctly converted by jira2markdown.

Thanks for noting - it seems related to the spaces in the Jira link syntax:

```
[GitHub PR 14495 | https://github.com/apache/arrow/pull/14495] adds support ...
```

I'm not sure how prevalent this is, or how easily it is addressed, but I've opened https://github.com/apache/arrow/issues/14711 to track it.

> Another jira2markdown one: it seems the converter cannot handle JIRA markup like {{{}code{}}}

Thanks, I've opened https://github.com/apache/arrow/issues/14712 to track this.

**Comment by pitrou** [comment]
Can we also try to migrate the JIRA labels `good-first-issue` and `good-second-issue`? They are useful to mark issues suitable for fledgling contributors.

**Comment by toddfarmer** [comment]
> Can we also try to migrate the JIRA labels `good-first-issue` and `good-second-issue`? They are useful to mark issues suitable for fledgling contributors.

Good suggestion! I've created https://github.com/apache/arrow/issues/14724 to track that.

**Comment by jorisvandenbossche** [comment]
Since it seems we also started to use some JIRAs to track work related to the migration / github usage, I updated the top post with a list of those as well

**Comment by rok** [comment]
I would like to propose we migrate Jira issues with [this script](https://github.com/rok/arrow-migration/blob/main/move_jira_issues_to_github.ipynb) some day in the coming week. I'll post to the ML as well.
Test processes take about 8 hours, mostly due to API call throttling.

[Test import](https://github.com/datatart/import_dry_run_4/issues) and some example issues [1](https://github.com/datatart/import_dry_run_4/issues/18178), [2](https://github.com/datatart/import_dry_run_4/issues/18190), [3](https://github.com/datatart/import_dry_run_4/issues/18191).

I think the key remaining questions are:
* Assignee / watcher treatment, see #14510
* Missing labels, see #14593

**Comment by wgtmac** [comment]
> I would like to propose we migrate Jira issues with [this script](https://github.com/rok/arrow-migration/blob/main/move_jira_issues_to_github.ipynb) some day in the coming week. I'll post to the ML as well. Test processes take about 8 hours, mostly due to API call throttling.
> 
> [Test import](https://github.com/datatart/import_dry_run_4/issues) and some example issues [1](https://github.com/datatart/import_dry_run_4/issues/18178), [2](https://github.com/datatart/import_dry_run_4/issues/18190), [3](https://github.com/datatart/import_dry_run_4/issues/18191).
> 
> I think the key remaining questions are:
> 
> * Assignee / watcher treatment, see [MIGRATION: Evaluate user mapping #14510](https://github.com/apache/arrow/issues/14510)
> * Missing labels, see [MIGRATION: Retain issue priority? #14593](https://github.com/apache/arrow/issues/14593)

@rok Quick question: will JIRAs opened for the parquet-cpp be migrated as well?
e.g. https://issues.apache.org/jira/browse/PARQUET-2225

**Comment by raulcd** [comment]
At the moment we are not migrating the PARQUET issues and the workflows are being updated to support GitHub issues for ARROW and JIRA issues for PARQUET but that is a conversation I would like to start (on the mailing list probably) to discuss how we could manage those simplifying the workflows. Having parquet-cpp on its own repo or fully integrated on ARROW (not a separate JIRA project) are some possible solutions but not sure if the tradeoffs are something we want to deal with.

**Comment by rok** [comment]
With the `master` -> `main` change complete we can probably close this out too?

**Comment by nealrichardson** [comment]
> With the `master` -> `main` change complete we can probably close this out too?

Weren't there some follow up tasks to update website and docs to say main, and remove some "master|main" code? Or have those been done too?

**Comment by assignUser** [comment]
Those remaining tasks are tracked here https://github.com/apache/arrow/issues/31142 

This issue can be closed. Thanks to everyone for the good work!
