### ISSUE TITLE
[JS] Reduce number of dependencies

### ISSUE THREAD

**Issue by asfimport** [apache/arrow#19639]
I installed the dependencies for arrow js today and it took 10 minutes (5 minutes the for the second run) with npm and less than one minute with yarn (I think there is an argument for using yarn instead of npm). Arrow js has 2792 dependencies right now. Installation takes very long but there is also some danger that the library will be hard to maintain in the future with this many dependencies. 

**Reporter**: [Dominik Moritz](https://issues.apache.org/jira/browse/ARROW-3302) / @domoritz
#### Subtasks:
- [X] [[JS] Remove Webpack dependency](https://github.com/apache/arrow/issues/21072)
- [X] [[JS] Remove npm-run-all](https://github.com/apache/arrow/issues/28080)
- [X] [[JS] Remove shx, trash, and rimraf](https://github.com/apache/arrow/issues/28088)
#### Related issues:
- [[JS] remove rxjs and ix dependency or make them lighter](https://github.com/apache/arrow/issues/28079) (is a parent of)
- [[JS] Remove @std/esm](https://github.com/apache/arrow/issues/19874) (relates to)

<sub>**Note**: *This issue was originally created as [ARROW-3302](https://issues.apache.org/jira/browse/ARROW-3302). Please see the [migration documentation](https://github.com/apache/arrow/issues/14542) for further details.*</sub>

**Comment by domoritz** [comment]
Installing dependencies now takes 6 seconds on my M1 Mac.
