### ISSUE TITLE
[C++] Improve C++ Orc Adapter performance and memory footprint

### ISSUE THREAD

**Issue by asfimport** [apache/arrow#21238]
Currently the Arrow C++ provide a naive adapter implementation that allow user to read orc file to Arrow RecordBatch. However, this implementation have several drawbacks:
- Inefficient conversion that incurs huge memcpy overhead
  - currently the ORC adapter are performing byte to byte memcpy to move data to ORC VectorBatch to Arrow RecordBatch regardless of the fact that ORC VectorBatch shares the same memory layout with Arrow in most of the Data Types
- Huge memory footprint because the lack of TableReader implementation
  - The ORC adapter currently only allow user to read data with the unit of stripe. However, as a columnar format with high compression ration, data read from a ORC stripe can potential takes over gigabytes of memory, which makes the ORC adapter not quite usable in production environment.
    
    Here we propose a new ORC adapter implementation to fix the issues mentioned above:
- To reduce conversion overhead, instead of performing naive data copy, the new adapter would be able to fully taking advantage of the memory layout similarity between ORC VectorBatch and Arrow RecordBatch. Namely the new adapter will perform pointer manipulation to transfer the memory ownership from VectorBatch to Arrow RecordBatch whenever possible.
- The new ORC Adapter would be able to provide user a row level granularity when reading data from Orc File. The user should be able to specify how many rows should be expected on output RecordBatch and the ORC Adapter should make sure no more the requested number of rows would be returned.

**Reporter**: [Yurui Zhou](https://issues.apache.org/jira/browse/ARROW-4713) / @yuruiz
#### Subtasks:
- [ ] [[C++][ORC] Enable copy free conversion for primitive types](https://github.com/apache/arrow/issues/21289)
- [ ] [[C++][ORC] Enable copy free conversion for Composite type](https://github.com/apache/arrow/issues/21290)
- [X] [Provide new ORC adapter interface that allow user to specify row number](https://github.com/apache/arrow/issues/21291)
- [ ] [[C++] Enable copy free conversion for dictionary encoded string column in ORC adapter](https://github.com/apache/arrow/issues/21292)
#### PRs and other links:
- [GitHub Pull Request #3843](https://github.com/apache/arrow/pull/3843)

<sub>**Note**: *This issue was originally created as [ARROW-4713](https://issues.apache.org/jira/browse/ARROW-4713). Please see the [migration documentation](https://github.com/apache/arrow/issues/14542) for further details.*</sub>

**Comment by XinyuZeng** [comment]
@iajoiner Do you still plan working on this?

**Comment by iajoiner** [comment]
@XinyuZeng Sorry I don't really have time for ORC right now. Please go ahead and take it if you want to.

**Comment by wgtmac** [comment]
take
