### ISSUE TITLE
[C++] Remove pointer aliases 

### ISSUE THREAD

**Issue by asfimport** [apache/arrow#23709]
**Reporter**: [Francois Saint-Jacques](https://issues.apache.org/jira/browse/ARROW-7438) / @fsaintjacques
#### Subtasks:
- [X] [[C++][Dataset] Remove dataset pointer aliases](https://github.com/apache/arrow/issues/23710)
- [ ] [[C++][Gandiva] Remove gandiva pointer aliases](https://github.com/apache/arrow/issues/23711)
- [ ] [[C++] Remove compute pointer aliases](https://github.com/apache/arrow/issues/23712)

<sub>**Note**: *This issue was originally created as [ARROW-7438](https://issues.apache.org/jira/browse/ARROW-7438). Please see the [migration documentation](https://github.com/apache/arrow/issues/14542) for further details.*</sub>
