### ISSUE TITLE
[C++] Native database interfaces

### ISSUE THREAD

**Issue by asfimport** [apache/arrow#27533]
Meta-task for adding native database interfaces to Arrow C++.

**Reporter**: [Antoine Pitrou](https://issues.apache.org/jira/browse/ARROW-11670) / @pitrou
#### Subtasks:
- [ ] [[C++] Native result set adapter for PostgreSQL / libpq](https://github.com/apache/arrow/issues/16693)
- [ ] [[C++] Native Arrow interface to sqlite3](https://github.com/apache/arrow/issues/19458)
- [ ] [[C++] Native client interface to SQL Server / TDS protocol](https://github.com/apache/arrow/issues/19503)
- [ ] [[C++] Native client interface to Clickhouse](https://github.com/apache/arrow/issues/19504)
- [ ] [[C++] Native database client for MariaDB / MySQL client protocol](https://github.com/apache/arrow/issues/19538)
#### Related issues:
- [[C++][Python][FlightRPC] Add Flight SQL ADBC driver and Python bindings](https://github.com/apache/arrow/issues/32901) (is related to)

<sub>**Note**: *This issue was originally created as [ARROW-11670](https://issues.apache.org/jira/browse/ARROW-11670). Please see the [migration documentation](https://github.com/apache/arrow/issues/14542) for further details.*</sub>

**Comment by thisisnic** [comment]
Closing this as I think it's superceded by ADBC
