### ISSUE TITLE
[Documentation] Documentation Improvements

### ISSUE THREAD

**Issue by asfimport** [apache/arrow#29076]
Parent ticket for general documentation improvement tasks

**Reporter**: [Nicola Crane](https://issues.apache.org/jira/browse/ARROW-13407) / @thisisnic
#### Subtasks:
- [X] [[R] Add examples to functions which don't have examples](https://github.com/apache/arrow/issues/29055)
- [X] [[R] Update arrow.Rmd vignette](https://github.com/apache/arrow/issues/29067)
- [X] [[R] Update install.Rmd vignette](https://github.com/apache/arrow/issues/29068)
- [X] [[R] Update dataset.Rmd vignette](https://github.com/apache/arrow/issues/29069)
- [X] [[R] Update fs.Rmd (Working with S3) vignette](https://github.com/apache/arrow/issues/29070)
- [X] [[R] Update python.Rmd vignette](https://github.com/apache/arrow/issues/29071)
- [X] [[R] Update flight.Rmd vignette](https://github.com/apache/arrow/issues/29072)
- [X] [[R] Update developing.Rmd vignette](https://github.com/apache/arrow/issues/29073)
- [X] [[R][Documentation] Document the process of creating R bindings for compute kernels and rationale behind conventions](https://github.com/apache/arrow/issues/18814)
- [X] [[R] Add our philosophy to the dev vignette](https://github.com/apache/arrow/issues/30004)
- [X] [[R][Docs] Add article on how to run R with C++ debugger to dev docs](https://github.com/apache/arrow/issues/30196)
- [X] [[R] Split dev docs into separate articles under developers menu](https://github.com/apache/arrow/issues/30252)
- [X] [[R] Add section to how to get output when things hang to debugger docs](https://github.com/apache/arrow/issues/30271)
- [X] [[Doc][Python] Make return types clickable](https://github.com/apache/arrow/issues/30275)
#### Related issues:
- [[Doc][Python] make clean doesn't clean up "generated" documentation](https://github.com/apache/arrow/issues/29011) (is a parent of)
- [[Python] [Doc] Make Python landing page less coupled to the rest of arrow documentation](https://github.com/apache/arrow/issues/18749) (is a parent of)
- [[Doc] Make "Libraries" the entry point for the documentation](https://github.com/apache/arrow/issues/29074) (is a parent of)
- [[Doc][Python] Ensure that ipc/io documentation uses context managers instead of manually closing streams](https://github.com/apache/arrow/issues/29139) (is a parent of)
- [[Python][Doc] Make docstrings conform to same style](https://github.com/apache/arrow/issues/29276) (is a parent of)
- [[Doc][Python] Make docs release match arrow releases](https://github.com/apache/arrow/issues/29080) (is a parent of)

<sub>**Note**: *This issue was originally created as [ARROW-13407](https://issues.apache.org/jira/browse/ARROW-13407). Please see the [migration documentation](https://github.com/apache/arrow/issues/14542) for further details.*</sub>
