### ISSUE TITLE
[Python] Remove deprecated APIs

### ISSUE THREAD

**Issue by asfimport** [apache/arrow#29205]
Remove APIs that have been deprecated for long enough.
This probably includes the old filesystem layer as well as the custom serialization layer.

**Reporter**: [Antoine Pitrou](https://issues.apache.org/jira/browse/ARROW-13555) / @pitrou
#### Subtasks:
- [x] [[Python] Remove deprecated pyarrow.serialization functionality](https://github.com/apache/arrow/issues/29705)
- [x] [[Python] Remove the deprecated pyarrow.filesystem legacy implementations](https://github.com/apache/arrow/issues/20127)
- [X] [[Python] Remove deprecated APIs from <= 1.0.0](https://github.com/apache/arrow/issues/32322)
- [X] [[Python] Remove remaining deprecated APIs from <= 1.0.0](https://github.com/apache/arrow/issues/32890)

<sub>**Note**: *This issue was originally created as [ARROW-13555](https://issues.apache.org/jira/browse/ARROW-13555). Please see the [migration documentation](https://github.com/apache/arrow/issues/14542) for further details.*</sub>

**Comment by AlenkaF** [comment]
Closing this issue as all subtasks are completed.
