### ISSUE TITLE
[R] Try to arrow_eval user-defined functions

### ISSUE THREAD

**Issue by asfimport** [apache/arrow#29667]
**Proposed approach**:
- Investigate simple injection with `!!`
- Investigate injection with `rlang::inject()`
- Investigate the data mask levels approach
- investigate other (undefined) approaches
  
**Original description**:
The first test passes but the second one fails, even though they're equivalent. The user's function isn't being evaluated in the nse_funcs environment.

```Java

  expect_dplyr_equal(
    input %>%
      select(-fct) %>%
      filter(nchar(padded_strings) < 10) %>%
      collect(),
    tbl
  )
  isShortString <- function(x) nchar(x) < 10
  expect_dplyr_equal(
    input %>%
      select(-fct) %>%
      filter(isShortString(padded_strings)) %>%
      collect(),
    tbl
  )
```

**Reporter**: [Neal Richardson](https://issues.apache.org/jira/browse/ARROW-14071) / @nealrichardson
**Assignee**: [Dragoș Moldovan-Grünfeld](https://issues.apache.org/jira/browse/ARROW-14071) / @dragosmg
#### Subtasks:
- [X] [[R] Investigate simple injection with !!](https://github.com/apache/arrow/issues/32241)
- [X] [[R] Investigate injection with rlang::inject()](https://github.com/apache/arrow/issues/32242)
- [X] [[R] Investigate the data mask levels approach](https://github.com/apache/arrow/issues/32243)
- [X] [[R] Investigate other (undefined) approaches](https://github.com/apache/arrow/issues/32244)
#### Related issues:
- [[R] Allow unrecognized R expressions to be callable as compute::Functions](https://github.com/apache/arrow/issues/20372) (relates to)
- [[R] arrow_eval user-defined generic functions  ](https://github.com/apache/arrow/issues/33156) (is related to)
#### PRs and other links:
- [GitHub Pull Request #13789](https://github.com/apache/arrow/pull/13789)
- [GitHub Pull Request #13960](https://github.com/apache/arrow/pull/13960)

<sub>**Note**: *This issue was originally created as [ARROW-14071](https://issues.apache.org/jira/browse/ARROW-14071). Please see the [migration documentation](https://github.com/apache/arrow/issues/14542) for further details.*</sub>
