### ISSUE TITLE
[R] [CI] Ensure we run all of CRAN's extended checks

### ISSUE THREAD

**Issue by asfimport** [apache/arrow#30089]
https://cran.r-project.org/web/checks/check_issue_kinds.html

**Reporter**: [Jonathan Keane](https://issues.apache.org/jira/browse/ARROW-14534) / @jonkeane
#### Subtasks:
- [X] [[R] [CI] Alternative BLAS/LAPACK implementations ](https://github.com/apache/arrow/issues/30090)
- [X] [[R] [CI] M1 tests](https://github.com/apache/arrow/issues/30091)
- [ ] [[R] [CI] Confirm that our sanitizer jobs are as close to CRAN as possible](https://github.com/apache/arrow/issues/30092)
- [X] [[R] [CI] R-devel with --disable-long double](https://github.com/apache/arrow/issues/18919)
- [X] [[R] [CI] R-devel with --disable-openmp](https://github.com/apache/arrow/issues/30097)
- [ ] [[R] [CI] Check without any of the suggested packages](https://github.com/apache/arrow/issues/30098)
- [ ] [[R] [CI] rcnst checks](https://github.com/apache/arrow/issues/30099)
- [ ] [[R] [CI] Check with a read only library](https://github.com/apache/arrow/issues/30100)

<sub>**Note**: *This issue was originally created as [ARROW-14534](https://issues.apache.org/jira/browse/ARROW-14534). Please see the [migration documentation](https://github.com/apache/arrow/issues/14542) for further details.*</sub>

**Comment by pitrou** [comment]
@jonkeane Do you think this issue is worth keeping open?

**Comment by jonkeane** [comment]
Probably not prospectively / the CRAN ecosystem has evolved enough that there are new + different checks we should add if we were going for completion. I'll close, and if we get bumped for any of these we can (+ will) add the relevant jobs)
