### ISSUE TITLE
[R] Implement bindings for stringr's combining strings functions

### ISSUE THREAD

**Issue by asfimport** [apache/arrow#30367]
**Reporter**: [Dragoș Moldovan-Grünfeld](https://issues.apache.org/jira/browse/ARROW-14837) / @dragosmg
#### Subtasks:
- [ ] [[R] Implement bindings for stringr::str_flatten](https://github.com/apache/arrow/issues/30387)
- [ ] [[R] Implement bindings for stringr::str_glue](https://github.com/apache/arrow/issues/30388)
- [ ] [[R] Implement bindings for stringr::str_glue_data](https://github.com/apache/arrow/issues/30389)
#### Related issues:
- [[R] stringr functions](https://github.com/apache/arrow/issues/30664) (is a child of)

<sub>**Note**: *This issue was originally created as [ARROW-14837](https://issues.apache.org/jira/browse/ARROW-14837). Please see the [migration documentation](https://github.com/apache/arrow/issues/14542) for further details.*</sub>

**Comment by thisisnic** [comment]
Closing this because we originally opened a series of tickets for all of stringrs functionality.  However,  we haven't seen any user interest in it, but if anyone would like to see it implemented, please comment below or reopen the issue.

**Comment by brunomioto** [comment]
Hello,

Nowadays I think more users (like me) would like to use these functions in arrow.

Thanks!

**Comment by thisisnic** [comment]
Awesome, would you like to submit a PR @brunomioto?
