### ISSUE TITLE
[R] Implement bindings for stringr's locale aware functions

### ISSUE THREAD

**Issue by asfimport** [apache/arrow#30393]
**Reporter**: [Dragoș Moldovan-Grünfeld](https://issues.apache.org/jira/browse/ARROW-14865) / @dragosmg
#### Subtasks:
- [X] [[R] Bindings for stringr::str_to_sentence](https://github.com/apache/arrow/issues/29256)
- [ ] [[R] Implement bindings for stringr::str_equal](https://github.com/apache/arrow/issues/30394)
- [ ] [[R] Implement bindings for stringr::str_order](https://github.com/apache/arrow/issues/30395)
- [ ] [[R] Implement bindings for stringr::str_sort](https://github.com/apache/arrow/issues/18963)
#### Related issues:
- [[R] stringr functions](https://github.com/apache/arrow/issues/30664) (is a child of)

<sub>**Note**: *This issue was originally created as [ARROW-14865](https://issues.apache.org/jira/browse/ARROW-14865). Please see the [migration documentation](https://github.com/apache/arrow/issues/14542) for further details.*</sub>
