### ISSUE TITLE
[C++] Simplify ExecPlan's C++ interface

### ISSUE THREAD

**Issue by asfimport** [apache/arrow#30751]
In recent work documenting the ExecPlan interface (ARROW-15091) and in trying to make a simple example using it (https://github.com/apache/arrow/issues/11799) we are seeing some rough edges.  This parent issue will track a number of subtasks that should make the C++ API easier to work with.

**Reporter**: [Weston Pace](https://issues.apache.org/jira/browse/ARROW-15257) / @westonpace
#### Subtasks:
- [X] [[C++] Easy options to create a source node from a table](https://github.com/apache/arrow/issues/30752)
- [ ] [[C++] Simplify creating a scan node](https://github.com/apache/arrow/issues/30755)
- [X] [[C++] Create a ToTable sink node](https://github.com/apache/arrow/issues/30756)
- [ ] [[C++] Add ExecNode to arrow/compute/api.h](https://github.com/apache/arrow/issues/30757)
- [X] [[C++] The write node options shouldn't require a schema](https://github.com/apache/arrow/issues/20066)
- [X] [[C++] Update ExecPlan example code and documentation with new options](https://github.com/apache/arrow/issues/30988)
#### Related issues:
- [[C++] Create "engine" module for the query engine](https://github.com/apache/arrow/issues/30735) (depends upon)

<sub>**Note**: *This issue was originally created as [ARROW-15257](https://issues.apache.org/jira/browse/ARROW-15257). Please see the [migration documentation](https://github.com/apache/arrow/issues/14542) for further details.*</sub>
