### ISSUE TITLE
[C++] Migrate Flight APIs to Result<>

### ISSUE THREAD

**Issue by asfimport** [apache/arrow#31074]
A number of Flight APIs use the convention of returning a `Status` and filling an actual return value in a pointer-out (`T*`) parameter. They should be migrated to returning `Result<T>` instead, together with a deprecation notice on the legacy API.

Examples are `BasicAuth::Serialize`, `BasicAuth::Deserialize`, `Location::Parse`, etc.

**Reporter**: [Antoine Pitrou](https://issues.apache.org/jira/browse/ARROW-15612) / @pitrou
#### Subtasks:
- [X] [[C++] Migrate flight/types.h header definitions to use Result<>](https://github.com/apache/arrow/issues/31399)
- [X] [[C++] Migrate FlightClient API to Result<>](https://github.com/apache/arrow/issues/31451)
- [X] [[C++] Migrate remaining flight API to use Resut<>](https://github.com/apache/arrow/issues/31482)
- [X] [[C++][FlightRPC] Migrate remaining flight API to use Result<>](https://github.com/apache/arrow/issues/31483)
- [x] [[C++][FlightRPC] Migrate SQL Client API to Result<>](https://github.com/apache/arrow/issues/31521)

<sub>**Note**: *This issue was originally created as [ARROW-15612](https://issues.apache.org/jira/browse/ARROW-15612). Please see the [migration documentation](https://github.com/apache/arrow/issues/14542) for further details.*</sub>

**Comment by RobertLD** [comment]
Considering the last of these subtasks was closed out with https://github.com/apache/arrow/commit/33ddff37f616123f623f922c2317b03f87a88489 , I think this issue can be closed as done?

**Comment by kou** [comment]
Good catch. Let's close this.
