### ISSUE TITLE
[Dev] Rename default branch to 'main'

### ISSUE THREAD

**Issue by asfimport** [apache/arrow#31142]
Parent issue, see subtasks

**Reporter**: [Neal Richardson](https://issues.apache.org/jira/browse/ARROW-15689) / @nealrichardson
#### Subtasks:
- [X] https://github.com/apache/arrow/issues/31143
- [X] https://github.com/apache/arrow/issues/31144
- [X] https://github.com/apache/arrow/issues/31145
- [X] https://github.com/apache/arrow/issues/31146
- [X] https://github.com/apache/arrow/issues/31147
- [x] https://github.com/apache/arrow/issues/20117
- [x] https://github.com/apache/arrow/issues/31148
- [x] https://github.com/apache/arrow/issues/31412
- [x] https://github.com/apache/arrow/issues/20161
- [x] https://github.com/apache/arrow/issues/32804
- [x] https://github.com/apache/arrow/issues/33005
- [x]  #33215
- [x] #34256
- [x] #34257

<sub>**Note**: *This issue was originally created as [ARROW-15689](https://issues.apache.org/jira/browse/ARROW-15689). Please see the [migration documentation](https://github.com/apache/arrow/issues/14542) for further details.*</sub>

**Comment by jorisvandenbossche** [comment]
I opened https://issues.apache.org/jira/browse/INFRA-24214 to ask for the rename, and https://github.com/apache/arrow/pull/34218 to rename all occurences in our own repo (but short term those urls also get redirected by github)

**Comment by assignUser** [comment]
I have added a few follow ups. Tagging @kevingurney and @lafiona so they are aware where this is tracked and how it is moving forward!

**Comment by kevingurney** [comment]
I've taken ownership of #31412 !

**Comment by jorisvandenbossche** [comment]
That reminds me that we also at some point need to ask INFRA for switching the branch name on the arrow-site repo as well. Are we ready to do that? Or are there still tasks to be done in preparation?

**Comment by assignUser** [comment]
It looks like the site workflows were already prepared to work with main instead of master.  I don't see anything else depending on the default branch there but I am not super familiar with that repo so not 100% certain.

**Comment by kevingurney** [comment]
@jorisvandenbossche and @assignUser - I'll verify that there aren't any remaining dependencies in the arrow-site workflows as part of my investigation of #31412.

**Comment by kevingurney** [comment]
Following up on this discussion:

1. I verified that the `apache/arrow-site` deployment workflows in `.github/workflows/deploy.yml` are already prepared to work with "main" or "master". See [line 23](https://github.com/apache/arrow-site/blob/032d5d697b1acd7c458c56cfa9cd5b29362553d6/.github/workflows/deploy.yml#L23) and [line 51](https://github.com/apache/arrow-site/blob/032d5d697b1acd7c458c56cfa9cd5b29362553d6/.github/workflows/deploy.yml#L51). Note that the Jira issue `ARROW-15988`, which is referred to in the comments on these lines, is now being tracked as #31412 in GitHub Issues. However, this issue can't be addressed until the default branch has been renamed to "main". Therefore, I'll follow up with a PR to address this as soon as Apache INFRA has renamed the default branch of the `apache/arrow-site` repo to "main".

2. I also did an investigation of #20161, which I captured in [this comment](https://github.com/apache/arrow/issues/20161#issuecomment-1442307810). From a CI / deployment workflow stand point, none of the uses of "master" listed in the comment linked to above should be blocking renaming the default branch of the `apache/arrow-site` repo to "main". However, since some of the hard-coded uses of "master" in the website content can't be removed until the default branch has been renamed, there will be a short period of time where some of the website content will be referring to "master" even when the default branch name has been changed to "main". This would be a temporary state, and I can create a PR to address #20161 as soon as the default branch has been renamed if the community is OK with this approach.

3. I also did a high level search for [references to `arrow-site` in the `apache/arrow` code base](https://github.com/apache/arrow/search?q=arrow-site) and none of the references appear to be dependent on "master".

---

**Summary**:

Given the analysis above, I believe we are ready to request INFRA to rename the default branch for the `apache/arrow-site` repo to "main".

Once the rename is complete, I can follow up with PRs to remove remaining uses of "master" from the website content and deployment workflows, addressing #20161 and #31412.

**Comment by assignUser** [comment]
Nice!
> there will be a short period of time where some of the website content will be referring to "master" even when the default branch name has been changed to "main". 

The links should continue to work as github forwards them afaik. So I agree that we are good to go, I'll open an infra ticket.

**Comment by jorisvandenbossche** [comment]
https://github.com/apache/arrow-site is now also using `main`

**Comment by kevingurney** [comment]
With the rename complete, I'll proceed with addressing https://github.com/apache/arrow/issues/20161 and https://github.com/apache/arrow/issues/31412.

**Comment by kevingurney** [comment]
I've opened PR apache/arrow-site#323 to address #31412.

**Comment by jorisvandenbossche** [comment]
Thanks @kevingurney !

**Comment by pitrou** [comment]
Everything has been done here, closing.
