### ISSUE TITLE
[Python] Deprecate the legacy ParquetDataset custom python-based implementation

### ISSUE THREAD

**Issue by asfimport** [apache/arrow#31529]
To be able to remove the custom python implementation (ARROW-15868), we first need to deprecate the various aspects. 

This issue is meant as a parent issue to keep an overview of the different tasks.

**Reporter**: [Joris Van den Bossche](https://issues.apache.org/jira/browse/ARROW-16119) / @jorisvandenbossche
#### Subtasks:
- [X] [[Python] Start with deprecating ParquetDataset custom attributes](https://github.com/apache/arrow/issues/18710)
- [X] [[Python] Start to raise deprecation warnings when using use_legacy_dataset=True in parquet.py](https://github.com/apache/arrow/issues/20143)
- [X] [[Python] Start raising deprecation warnings for ParquetDataset keywords that won't be supported with the new API](https://github.com/apache/arrow/issues/31305)
- [X] [[Python] ParquetDataset deprecation: change Deprecation to FutureWarnings](https://github.com/apache/arrow/issues/31530)
- [X] [[Python] Deprecate the (common_)metadata(_path) attributes of ParquetDataset](https://github.com/apache/arrow/issues/20181)
- [X] [[Python] Change use_legacy_dataset default and deprecate no-longer supported keywords in parquet.write_to_dataset](https://github.com/apache/arrow/issues/31531)
- [X] [[Python] Support row_group_size/chunk_size keyword in pq.write_to_dataset with use_legacy_dataset=False](https://github.com/apache/arrow/issues/31636)
- [X] [[Python] Switch default and deprecate use_legacy_dataset=True in ParquetDataset](https://github.com/apache/arrow/issues/32067)
- 
#### Related issues:
- https://github.com/apache/arrow/issues/31303 (blocks)
- https://github.com/apache/arrow/issues/25775 (is a child of)
- https://github.com/apache/arrow/issues/20233 (is required by)

<sub>**Note**: *This issue was originally created as [ARROW-16119](https://issues.apache.org/jira/browse/ARROW-16119). Please see the [migration documentation](https://github.com/apache/arrow/issues/14542) for further details.*</sub>

**Comment by jorisvandenbossche** [comment]
Indeed, and we also warn when specifically choosing the legacy one.
