### ISSUE TITLE
[Python] Improving Classes and Methods Docstrings - Streams and File access

### ISSUE THREAD

**Issue by asfimport** [apache/arrow#31715]
Continuation of the initiative aimed at improving methods and classes docstrings, especially from the point of view of ensuring they have an `Examples` section.

Covered topic: Streams and File access

**Reporter**: [Alenka Frim](https://issues.apache.org/jira/browse/ARROW-16331) / @AlenkaF
#### Subtasks:
- [x] [[Python] Address docstrings in Streams and File Access (Factory Functions)](https://github.com/apache/arrow/issues/31506)
- [x] [[Python] Address docstrings in Streams and File Access  (Stream Classes)](https://github.com/apache/arrow/issues/31507)
- [X] [[Python] Address docstrings in Streams and File Access (FileSystems)](https://github.com/apache/arrow/issues/31508)

<sub>**Note**: *This issue was originally created as [ARROW-16331](https://issues.apache.org/jira/browse/ARROW-16331). Please see the [migration documentation](https://github.com/apache/arrow/issues/14542) for further details.*</sub>
