### ISSUE TITLE
[Python] Improving Classes and Methods Docstrings - Type Classes

### ISSUE THREAD

**Issue by asfimport** [apache/arrow#32356]
Continuation of the initiative aimed at improving methods and classes docstrings, especially from the point of view of ensuring they have an `Examples` section.

This is an umbrella issue for tickets that cover specific [type classes](https://arrow.apache.org/docs/python/api/datatypes.html#type-classes) and could be worked on after https://issues.apache.org/jira/browse/ARROW-16331.

**Reporter**: [Alenka Frim](https://issues.apache.org/jira/browse/ARROW-17048) / @AlenkaF
#### Subtasks:

- [X] [[Python][Docs] Document how to get field from StructType](https://github.com/apache/arrow/issues/32355)
- [x] https://github.com/apache/arrow/issues/33741
- [x] https://github.com/apache/arrow/issues/33742

<sub>**Note**: *This issue was originally created as [ARROW-17048](https://issues.apache.org/jira/browse/ARROW-17048). Please see the [migration documentation](https://github.com/apache/arrow/issues/14542) for further details.*</sub>
