### ISSUE TITLE
[C++] Move to C++17

### ISSUE THREAD

**Issue by asfimport** [apache/arrow#32415]
The upcoming abseil release has dropped support for C++11, so {_}eventually{_}, arrow will have to follow. More details [here](https://github.com/conda-forge/abseil-cpp-feedstock/issues/37).

Relatedly, when I [tried](https://github.com/conda-forge/abseil-cpp-feedstock/pull/25) to switch abseil to a newer C++ version on windows, things apparently broke in arrow CI. This is because the ABI of abseil is sensitive to the C++ standard that's used to compile, and google only supports a homogeneous version to compile all artefacts in a stack. This creates some friction with conda-forge (where the compilers are generally much newer than what arrow might be willing to impose). For now, things seems to have worked out with arrow [specifying](https://github.com/apache/arrow/blob/897a4c0ce73c3fe07872beee2c1d2128e44f6dd4/cpp/cmake_modules/SetupCxxFlags.cmake#L121-L124) C\+\11 while conda-forge moved to C\\+17 - at least on unix, but windows was not so lucky.

Perhaps people would therefore also be interested in collaborating (or at least commenting on) this [issue](https://github.com/conda-forge/abseil-cpp-feedstock/issues/29), which should permit more flexibility by being able to opt into given standard versions also from conda-forge.

**Update:**

It was voted on the dev ML to move to C++17:
- vote announcement:
  https://lists.apache.org/thread/h9v83rwdl015z2j6s8zwdr1qp4svb5j8
- vote result:
  https://lists.apache.org/thread/dod96gbqtfz7pf096vhlczq6f5hv81z8

**Reporter**: [H. Vetinari](https://issues.apache.org/jira/browse/ARROW-17110)
#### Subtasks:
- [X] [[C++][CI] Mandate C++17 instead of C++11](https://github.com/apache/arrow/issues/32798)
- [X] [[C++] Remove pre-C++17 compatibility measures](https://github.com/apache/arrow/issues/32799)
- [ ] [[C++] Adopt C++17 idioms and features for maintainability](https://github.com/apache/arrow/issues/32800)
#### Related issues:
- [[C++] C++14 laundry list](https://github.com/apache/arrow/issues/28552) (supercedes)

<sub>**Note**: *This issue was originally created as [ARROW-17110](https://issues.apache.org/jira/browse/ARROW-17110). Please see the [migration documentation](https://github.com/apache/arrow/issues/14542) for further details.*</sub>

**Comment by pitrou** [comment]
This was done some time ago, closing.
