### ISSUE TITLE
[C++] Adding ExecNode with Sort and Fetch capability

### ISSUE THREAD

**Issue by asfimport** [apache/arrow#32478]
In Substrait integrations with ACERO, a functionality required is the ability to fetch records sorted and unsorted.

Fetch operation is defined as selecting `K` number of records with an offset. For instance pick 10 records skipping the first 5 elements. Here we can define this as a Slice operation and records can be easily extracted in a sink-node. 

Sort and Fetch operation applies when we need to execute a Fetch operation on sorted data. The main issue is we cannot have a sort node followed by a fetch. The reason is that all existing node definitions supporting sort are based on sink nodes. Since there cannot be a node followed by sink, this functionality has to take place in a single node. 

But this is not a perfect solution for fetch and sort, but one way to do this is define a sink node where the records are sorted and then a set of items are fetched. 

Another dilema is what if sort is followed by a fetch. In that case, there has to be a flag to enable the order of the operations. 

The objective of this ticket is to discuss a viable efficient solution and include new nodes or a method to execute such a logic.

 

**Reporter**: [Vibhatha Lakmal Abeykoon](https://issues.apache.org/jira/browse/ARROW-17183) / @vibhatha
#### Subtasks:
- [x] [[C++] Create a Fetch Node](https://github.com/apache/arrow/issues/32484)
- [ ] [[Docs] Create Documentation for Fetch Sink Node](https://github.com/apache/arrow/issues/32489)
- [x] [[C++] Optimize Fetch Node to avoid collecting all records for non-sort setting](https://github.com/apache/arrow/issues/20337)

<sub>**Note**: *This issue was originally created as [ARROW-17183](https://issues.apache.org/jira/browse/ARROW-17183). Please see the [migration documentation](https://github.com/apache/arrow/issues/14542) for further details.*</sub>

**Comment by nealrichardson** [comment]
@westonpace this is redundant now, correct?

**Comment by westonpace** [comment]
Agreed
