### ISSUE TITLE
[R] User experience improvements

### ISSUE THREAD

**Issue by asfimport** [apache/arrow#33401]
Umbrella ticket to collect together tickets relating to improving error messages, and general user experience tweaks

**Reporter**: [Nicola Crane](https://issues.apache.org/jira/browse/ARROW-18215) / @thisisnic
#### Subtasks:
- [ ] [[R] Add as_scalar()](https://github.com/apache/arrow/issues/20396)
- [ ] [[R] Misleading error message in query using across()](https://github.com/apache/arrow/issues/33385)
- [ ] [[R] Better error message when creating an array from decimals](https://github.com/apache/arrow/issues/33402)

<sub>**Note**: *This issue was originally created as [ARROW-18215](https://issues.apache.org/jira/browse/ARROW-18215). Please see the [migration documentation](https://github.com/apache/arrow/issues/14542) for further details.*</sub>

**Comment by thisisnic** [comment]
This issue has been marked as stale because it has had no activity in the past 2 years. Please remove the stale label or comment below, or this issue will be closed in 14 days.
