### ISSUE TITLE
[R] CRAN packaging checklist for version 11.0.0.3

### ISSUE THREAD

**Issue by thisisnic** [apache/arrow#34372]
I've updated this to remove steps which won't be applicable for a patch release.

# Packaging checklist for CRAN release

For a high-level overview of the release process see the
[Apache Arrow Release Management Guide](https://arrow.apache.org/docs/developers/release.html#post-release-tasks).

Before the release candidate is cut:

- [x] [Create a GitHub issue](https://github.com/apache/arrow/issues/new/)
  entitled `[R] CRAN packaging checklist for version X.X.X`
  and copy this checklist to the issue.
- [x] Check [current CRAN check results](https://cran.rstudio.org/web/checks/check_results_arrow.html)
- [x] Ensure the contents of the README are accurate and up to date
- [x] Run `urlchecker::url_check()` on the R directory at the release candidate
  commit. Ignore any errors with badges as they will be removed in the CRAN release branch.
- [x] [Polish NEWS](https://style.tidyverse.org/news.html#news-release) + version numbers (as is patch release)

Wait for the release candidate to be cut:

- [x] Create a CRAN-release branch from the most recent CRAN-release branch

Prepare and check the .tar.gz that will be released to CRAN.

- [x] Run `make build`. This copies Arrow C++ into tools/cpp, prunes some
  unnecessary components, and runs `R CMD build` to generate the source tarball.
  Because this will install the package, you will need to ensure that the version
  of Arrow C++ available to the configure script is the same as the version
  that is vendored into the R package (e.g., you may need to unset `ARROW_HOME`).
- [x] `devtools::check_built("arrow_X.X.X.tar.gz")` locally
- [x] Run reverse dependency checks. Currently this is a 
  [manual process](https://gist.github.com/paleolimbot/630fdab1e204d70fea97633d8fa15ccb);
  however, in the future it may be a crossbow nightly job.

- [x] Remove badges from README.md
- [x] Run `urlchecker::url_check()` on the R directory
- [x] Create a PR entitled `WIP: [R] Verify CRAN release-10.0.1-rc0`. Add
  a comment `@github-actions crossbow submit --group r` to run all R crossbow
  jobs against the CRAN-specific release branch.
  https://github.com/apache/arrow/pull/34471
- [x] Regenerate arrow_X.X.X.tar.gz (i.e., `make build`)

Check binary Arrow C++ distributions specific to the R package:

- [x] Upload the .tar.gz to [win-builder](https://win-builder.r-project.org/upload.aspx) (r-devel only)
  and confirm (with Nic, who will automatically receive an email about the results) that the check is clean.
- [x] Upload the .tar.gz to [MacBuilder](https://mac.r-project.org/macbuilder/submit.html)
  and confirm that the check is clean
https://mac.r-project.org/macbuilder/results/1678187047-b1ee6ec9def3432e/
- [x] Check `install.packages("arrow_X.X.X.tar.gz")` on Ubuntu and ensure that the
  hosted binaries are used
- [x] `devtools::check_built("arrow_X.X.X.tar.gz")` locally one more time (for luck)

Submit!

- [x] Upload arrow_X.X.X.tar.gz to the
  [CRAN submit page](https://xmpalantir.wu.ac.at/cransubmit/)
- [x] Confirm the submission email

Wait for CRAN...

- [x] Accepted!
- [x] Tag the tip of the CRAN-specific release branch
- [x] (patch releases only) Update the package version in `ci/scripts/PKGBUILD`, `dev/tasks/homebrew-formulae/autobrew/apache-arrow.rb`, `r/DESCRIPTION`, and `r/NEWS.md`
- [x] Update the packaging checklist template to reflect any new realities of the
  packaging process.
- [x] Wait for CRAN-hosted binaries on the
  [CRAN package page](https://cran.r-project.org/package=arrow) to reflect the
  new version
