### ISSUE TITLE
[R] CRAN packaging checklist for version 12.0.0

### ISSUE THREAD

**Issue by paleolimbot** [apache/arrow#35216]
### Describe the enhancement requested

# Packaging checklist for CRAN release

For a high-level overview of the release process see the
[Apache Arrow Release Management Guide](https://arrow.apache.org/docs/developers/release.html#post-release-tasks).

Before the release candidate is cut:

- [x] [Create a GitHub issue](https://github.com/apache/arrow/issues/new/)
  entitled `[R] CRAN packaging checklist for version X.X.X`
  and copy this checklist to the issue.
- [x] Evaluate the status of any failing
  [nightly tests and nightly packaging builds](http://crossbow.voltrondata.com). These checks
  replicate most of the checks that CRAN runs, so we need them all to be passing
  or to understand that the failures may (though won't necessarily) result in a rejection from CRAN.
- [x] Check [current CRAN check results](https://cran.rstudio.org/web/checks/check_results_arrow.html)
- [x] Ensure the contents of the README are accurate and up to date
- [x] Run `urlchecker::url_check()` on the R directory at the release candidate
  commit. Ignore any errors with badges as they will be removed in the CRAN release branch.
- [x] [Polish NEWS](https://style.tidyverse.org/news.html#news-release) but do **not** update version numbers (this is done automatically later).
- [ ] For major releases, prepare tweet thread highlighting new features

Wait for the release candidate to be cut:

- [x] Release candidate!
- [x] Create a CRAN-release branch from the release candidate commit

Make pull requests into the [autobrew](https://github.com/autobrew) and
[rtools-packages](https://github.com/r-windows/rtools-packages) repositories
used by the configure script on MacOS and Windows. These pull requests will
use the release candidate as the source.

- [ ] Pull request to modify
  [the apache-arrow autobrew formula]( https://github.com/autobrew/homebrew-core/blob/high-sierra/Formula/apache-arrow.rb) 
  to update the release version, SHA256 checksum of the release source file (which can be found in the same directory as the release source file), and any changes to dependencies and build steps that have changed in the
  [copy of the formula we have of that formula in the Arrow repo](https://github.com/apache/arrow/blob/main/dev/tasks/homebrew-formulae/autobrew/apache-arrow.rb)
- [ ] Pull request to modify
  [the apache-arrow-static autobrew formula](https://github.com/autobrew/homebrew-cran/blob/master/Formula/apache-arrow-static.rb)
  to update the version, SHA, and any changes to dependencies and build steps that have changed in the
  [copy of the formula we have of that formula in the Arrow repo](https://github.com/apache/arrow/blob/main/dev/tasks/homebrew-formulae/autobrew/apache-arrow-static.rb)
- [ ] Pull request to modify the 
  [autobrew script](https://github.com/autobrew/scripts/blob/master/apache-arrow)
  to include any additions made to
  [r/tools/autobrew](https://github.com/apache/arrow/blob/main/r/tools/autobrew).
- [ ] Pull request to modify the
  [RTools PKGBUILD script](https://github.com/r-windows/rtools-packages/blob/master/mingw-w64-arrow/PKGBUILD)
  to reflect changes in
  [ci/PKGBUILD](https://github.com/apache/arrow/blob/main/ci/scripts/PKGBUILD),
  uncommenting the line that says "uncomment to test the rc".

Prepare and check the .tar.gz that will be released to CRAN.

- [x] `git fetch upstream && git checkout release-X.X.X-rcXX && git clean -f -d`
- [x] Run `make build`. This copies Arrow C++ into tools/cpp, prunes some
  unnecessary components, and runs `R CMD build` to generate the source tarball.
  Because this will install the package, you will need to ensure that the version
  of Arrow C++ available to the configure script is the same as the version
  that is vendored into the R package (e.g., you may need to unset `ARROW_HOME`).
- [x] `devtools::check_built("arrow_X.X.X.tar.gz")` locally
- [x] Run reverse dependency checks. Currently this is a 
  [manual process](https://gist.github.com/paleolimbot/630fdab1e204d70fea97633d8fa15ccb);
  however, in the future it may be a crossbow nightly job.

Wait for the official release...
  
- [x] Release vote passed!
- [x] If the release candidate commit updated, rebase the CRAN release branch
  on that commit.
- [x] Pick any commits that were made to main since the release commit that
  were needed to fix CRAN-related submission issues identified in the above
  steps.
- [x] Remove badges from README.md
- [x] Run `urlchecker::url_check()` on the R directory
- [x] [Create a PR entitled `WIP: [R] Verify CRAN release-10.0.1-rc0`. Add
  a comment `@github-actions crossbow submit --group r` to run all R crossbow
  jobs against the CRAN-specific release branch.](https://github.com/apache/arrow/pull/35402)
- [x] Regenerate arrow_X.X.X.tar.gz (i.e., `make build`)

Create new autobrew and r-windows PRs such that they use the *release*
instead of the *release candidate*; ensure linux binary packages are available:

- [x] PR into autobrew/homebrew-core (apache-arrow autobrew formula)
      https://github.com/autobrew/homebrew-core/pull/124
- [x] PR into autobrew/homebrew-core (apache-arrow-static autobrew formula)
      https://github.com/autobrew/homebrew-cran/pull/77
- [x] PR into autobrew/scripts
      https://github.com/autobrew/scripts/pull/15
- [x] PR into r-windows/rtools-packages
      https://github.com/r-windows/rtools-packages/pull/280
- [x] Ensure linux binaries are available in the artifactory:
  https://apache.jfrog.io/ui/repos/tree/General/arrow/r

Check binary Arrow C++ distributions specific to the R package:

- [x] Upload the .tar.gz to [win-builder](https://win-builder.r-project.org/upload.aspx) (r-devel only)
  and confirm (with Nic, who will automatically receive an email about the results) that the check is clean.
  This step cannot be completed before Jeroen has put the binaries in the MinGW repository, i.e. [here](https://ftp.opencpu.org/rtools/ucrt64/), [here](https://ftp.opencpu.org/rtools/mingw64/), and [here](https://ftp.opencpu.org/rtools/mingw32/).
- [x] Upload the .tar.gz to [MacBuilder](https://mac.r-project.org/macbuilder/submit.html)
  and confirm that the check is clean
      https://mac.r-project.org/macbuilder/results/1683287726-628f7ff77aab0dd5/
- [x] Check `install.packages("arrow_X.X.X.tar.gz")` on Ubuntu and ensure that the
  hosted binaries are used
- [x] `devtools::check_built("arrow_X.X.X.tar.gz")` locally one more time (for luck)

Submit!

- [x] Upload arrow_X.X.X.tar.gz to the
  [CRAN submit page](https://xmpalantir.wu.ac.at/cransubmit/)
- [x] Confirm the submission email

Wait for CRAN...

- [x] Accepted!
- [x] Tag the tip of the CRAN-specific release branch
- [x] Add a new line to the matrix in the [backwards compatability job](https://github.com/apache/arrow/blob/main/dev/tasks/r/github.linux.arrow.version.back.compat.yml)
- [ ] (patch releases only) Update the package version in `ci/scripts/PKGBUILD`, `dev/tasks/homebrew-formulae/autobrew/apache-arrow.rb`, `r/DESCRIPTION`, and `r/NEWS.md`
- [ ] (CRAN-only releases) Rebuild the docs with `pkgdown::build_site(examples = FALSE, lazy = TRUE, install = FALSE)` and submit a PR to [the `asf-site` branch of the docs site](https://github.com/apache/arrow-site) with the contents of `r/docs/news/index.html`.
- [ ] (CRAN-only releases) Bump the version number in `r/pkgdown/assets/versions.json`, and update this on the [the `asf-site` branch of the docs site](https://github.com/apache/arrow-site) too.
- [x] Update the packaging checklist template to reflect any new realities of the
  packaging process.
- [x] Wait for CRAN-hosted binaries on the   [CRAN package page](https://cran.r-project.org/package=arrow) to reflect the
  new version
- [x] Tweet!

### Component(s)

R

**Comment by paleolimbot** [comment]
For the first bit:

- Our nightlies are in good shape! 🤞  There's still the reported valgrind failure that I haven't gotten around to diagnosing.
- We don't have any CRAN package check issues that need fixing

We will need a fix for #35131 merged before CRAN submission. These are just test changes and so I'm not concerned if it does not merge before the RC vote. I will tackle that tomorrow.

**Comment by assignUser** [comment]
As a reminder: The relatively large acero changes need to be upstreamed to auto/homebrew: https://github.com/apache/arrow/pull/34844

**Comment by paleolimbot** [comment]
Our reverse dependencies as of a few days ago were 💯 according to the archery job! The only mandatory fix that will need to be done/picked into the CRAN packaging branch is https://github.com/apache/arrow/issues/35131 .

**Comment by thisisnic** [comment]
We also want https://github.com/apache/arrow/issues/35401 adding in

**Comment by thisisnic** [comment]
Added #35407 too

**Comment by paleolimbot** [comment]
I ran another reverse dependency check with the release branch...all clean!

The coolest thing is...we're up 10 reverse dependencies! (32 -> 42)

**Comment by thisisnic** [comment]
@paleolimbot That's excellent; what are our new ones?

**Comment by paleolimbot** [comment]
Totally hacked together summary:

```
1          analogsea TRUE TRUE
2              arkdb TRUE TRUE
3       CDMConnector TRUE TRUE
4     ClickHouseHTTP TRUE TRUE
5       dataversionr TRUE TRUE
6            diffdfs TRUE TRUE
7         disk.frame TRUE TRUE
8             duckdb TRUE TRUE
9          fastverse TRUE TRUE
10            gbifdb TRUE TRUE
11 MolgenisArmadillo TRUE TRUE
12   mrgsim.parallel TRUE TRUE
13          nflreadr TRUE TRUE
14            noctua TRUE TRUE
15           opencpu TRUE TRUE
16             parqr TRUE TRUE
17        parquetize TRUE TRUE
18              pins TRUE TRUE
19           plumber TRUE TRUE
20        pointblank TRUE TRUE
21           RAthena TRUE TRUE
22            raveio TRUE TRUE
23       receptiviti TRUE TRUE
24               rio TRUE TRUE
25           sfarrow TRUE TRUE
26          sparklyr TRUE TRUE
27            starvz TRUE TRUE
28            strand TRUE TRUE
29           targets TRUE TRUE
30         tidyquery TRUE TRUE
31   tradestatistics TRUE TRUE
32           vetiver TRUE TRUE
33         Andromeda   NA TRUE
34           brclimr   NA TRUE
35 CodelistGenerator   NA TRUE
36       dataverifyr   NA TRUE
37           foundry   NA TRUE
38            IGoRRR   NA TRUE
39            matric   NA TRUE
40         nanoarrow   NA TRUE
41                nc   NA TRUE
42               SQL   NA TRUE
```

**Comment by thisisnic** [comment]
All the 12.0.0-relevant bits here are done, so I'm closing this now
