### ISSUE TITLE
[Java] Flaky tests meta-issue

### ISSUE THREAD

**Issue by lidavidm** [apache/arrow#35945]
### Describe the enhancement requested

- [ ] https://github.com/apache/arrow/issues/28048
- [ ] https://github.com/apache/arrow/issues/33237
- [ ] https://github.com/apache/arrow/issues/33238
- [ ] https://github.com/apache/arrow/issues/34741
- [ ] https://github.com/apache/arrow/issues/35932

### Component(s)

Java
