### ISSUE TITLE
[R] CRAN packaging checklist for version 12.0.1.1

### ISSUE THREAD

**Issue by thisisnic** [apache/arrow#36733]
### Describe the bug, including details regarding any error messages, version, and platform.

# Packaging checklist for CRAN release

## Before the release candidate is cut

- [x] [Create a GitHub issue](https://github.com/apache/arrow/issues/new/) entitled `[R] CRAN packaging checklist for version X.X.X` and copy this checklist to the issue.
- [x] Evaluate the status of any failing [nightly tests and nightly packaging builds](http://crossbow.voltrondata.com). These checks replicate most of the checks that CRAN runs, so we need them all to be passing or to understand that the failures may (though won't necessarily) result in a rejection from CRAN.
- [x] Check [current CRAN check results](https://cran.rstudio.org/web/checks/check_results_arrow.html)
- [x] Ensure the contents of the README are accurate and up to date.
- [x] Run `urlchecker::url_check()` on the R directory at the release candidate.
  commit. Ignore any errors with badges as they will be removed in the CRAN release branch.
- [x] [Polish NEWS](https://style.tidyverse.org/news.html#news-release) but do **not** update version numbers (this is done automatically later).
- [x] Run preliminary reverse dependency checks using `archery docker run r-revdepcheck`.

## After release candidate has been cut
- [x] Create a CRAN-release branch from the release candidate commit

## Prepare and check the .tar.gz that will be released to CRAN.

- [x] `git fetch upstream && git checkout release-X.X.X-rcXX && git clean -f -d`
- [x] Run `make build`. This copies Arrow C++ into tools/cpp, prunes some
  unnecessary components, and runs `R CMD build` to generate the source tarball.
  Because this will install the package, you will need to ensure that the version
  of Arrow C++ available to the configure script is the same as the version
  that is vendored into the R package (e.g., you may need to unset `ARROW_HOME`).
- [x] `devtools::check_built("arrow_X.X.X.tar.gz")` locally
- [x] Run reverse dependency checks using `archery docker run r-revdepcheck`.

## Generate R package to submit to CRAN
- [x] Pick any commits that were made to main since the release commit that
  were needed to fix CRAN-related submission issues identified in the above
  steps.
- [x] Remove badges from README.md
- [x] Run `urlchecker::url_check()` on the R directory
- [x] Create a PR entitled `WIP: [R] Verify CRAN release-10.0.1-rc0`. Add
  a comment `@github-actions crossbow submit --group r` to run all R crossbow
  jobs against the CRAN-specific release branch.
- [x] Regenerate arrow_X.X.X.tar.gz (i.e., `make build`)
- [x] `devtools::check_built("arrow_X.X.X.tar.gz")` locally one more time (for luck)

- [x] Upload the .tar.gz to [win-builder](https://win-builder.r-project.org/upload.aspx) (r-devel only) and confirm (with Nic, who will automatically receive an email about the results) that the check is clean: 
- [x]    Upload the .tar.gz to [MacBuilder](https://mac.r-project.org/macbuilder/submit.html) and confirm that the check is clean: https://mac.r-project.org/macbuilder/results/1689683138-4b3a173ac6925063/

## CRAN submission
- [x] Upload arrow_X.X.X.tar.gz to the
  [CRAN submit page](https://xmpalantir.wu.ac.at/cransubmit/)
- [x] Confirm the submission email

Wait for CRAN...
- [x] Accepted!
- [x] Tag the tip of the CRAN-specific release branch
- [x] Add a new line to the matrix in the [backwards compatability job](https://github.com/apache/arrow/blob/main/dev/tasks/r/github.linux.arrow.version.back.compat.yml)
- [x] (patch releases only) Update the package version in `ci/scripts/PKGBUILD`, `dev/tasks/homebrew-formulae/autobrew/apache-arrow.rb`, `r/DESCRIPTION`, and `r/NEWS.md`
- [ ] (CRAN-only releases) Rebuild the docs with `pkgdown::build_site(examples = FALSE, lazy = TRUE, install = FALSE)` and submit a PR to [the `asf-site` branch of the docs site](https://github.com/apache/arrow-site) with the contents of `r/docs/news/index.html`.
- [ ] (CRAN-only releases) Bump the version number in `r/pkgdown/assets/versions.json`, and update this on the [the `asf-site` branch of the docs site](https://github.com/apache/arrow-site) too.
- [x] Update the packaging checklist template to reflect any new realities of the
  packaging process.
- [x] Wait for CRAN-hosted binaries on the
  [CRAN package page](https://cran.r-project.org/package=arrow) to reflect the
  new version

### Component(s)

R
