### ISSUE TITLE
[EPIC] Ensure compliance with ASF branding policy for all documentation and logos across all implementations and subprojects

### ISSUE THREAD

**Issue by andygrove** [apache/arrow#39462]
### Describe the enhancement requested

Some of our documentation across the Arrow project is not currently in line with ASF policy, in particular:

- [Trademark Attributions Policy](https://www.apache.org/foundation/marks/pmcs#attributions)
- [Logos and Graphics Policy](https://www.apache.org/foundation/marks/pmcs#graphics)

Since this affects multiple repositories and subprojects, I am creating this one epic to track all issues.

## Trademark Attribution

- [ ] https://github.com/apache/arrow/issues/39461 (monorepo)
- [x] https://github.com/apache/arrow-adbc/issues/1433 (ADBC)
- [x] https://github.com/apache/arrow-datafusion/issues/8755 (DataFusion)
- [x] https://github.com/apache/arrow-datafusion-python/issues/553 (DataFusion Python)
- [x] https://github.com/apache/arrow-ballista/issues/950 (Ballista)
- [x] https://github.com/apache/arrow-ballista-python/issues/64 (Ballista Python)
- [ ] https://github.com/apache/arrow-flight-sql-postgresql/issues/185 (Flight SQL adapter for PostgreSQL)

## Logos

- [ ] https://github.com/apache/arrow/issues/39459
- [x] https://github.com/apache/arrow-datafusion/issues/8754

TODO: check other subprojects (nanoarrow, julia, etc)

### Component(s)

Documentation, Website

**Comment by thisisnic** [comment]
This issue has been closed because there has been no activity for the 14 days since the stale warning. Feel free to reopen if this has been closed in error.
