### ISSUE TITLE
[C++][Parquet] LONE - [C++] Parquet modular encryption

### ISSUE THREAD

**Issue by asfimport** [apache/arrow#42965]
CPP version of a mechanism for modular encryption and decryption of Parquet files. Allows to keep the data fully encrypted in the storage, while enabling a client to extract a required subset (footer, column(s), pages) and to authenticate / decrypt the extracted data.

**Reporter**: [Akshay](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=akshaybadhe) / @akshaybadhe
**Assignee**: Deepak Majeti](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=mdeepak) / @majetideepak
#### Subtasks:
- [X] [CLONE - [C++] Crypto package in parquet-cpp](https://issues.apache.org/jira/browse/PARQUET-1907)
- [X] [CLONE - [C++] Update cpp crypto package to match signed-off specification](https://issues.apache.org/jira/browse/PARQUET-1908)
- [X] [CLONE - [C++] Add encrypted parquet files to apache parquet-testing repository](https://issues.apache.org/jira/browse/PARQUET-1909)
#### Related issues:
- [[C++] Parquet modular encryption](https://issues.apache.org/jira/browse/PARQUET-1300) (is a clone of)
- [Parquet modular encryption](https://issues.apache.org/jira/browse/PARQUET-1178) (is depended upon by)
#### Original Issue Attachments:
- [column_reader.cc](https://issues.apache.org/jira/secure/attachment/13011146/column_reader.cc)
- [column_writer.cc](https://issues.apache.org/jira/secure/attachment/13011147/column_writer.cc)
- [file_reader.cc](https://issues.apache.org/jira/secure/attachment/13011148/file_reader.cc)
- [file_writer.cc](https://issues.apache.org/jira/secure/attachment/13011149/file_writer.cc)
- [thrift.h](https://issues.apache.org/jira/secure/attachment/13011150/thrift.h)
#### PRs and other links:
- [GitHub Pull Request #2555](https://github.com/apache/arrow/pull/2555)
- [GitHub Pull Request #4826](https://github.com/apache/arrow/pull/4826)
- [GitHub Pull Request #475](https://github.com/apache/parquet-cpp/pull/475)
- [Design](https://docs.google.com/document/d/1T89G7xR0zHFV1f2pjTO28jtfVm8qoNVGEJQ70Rsk-bY/edit?usp=sharing)

<sub>**Note**: *This issue was originally created as [PARQUET-1906](https://issues.apache.org/jira/browse/PARQUET-1906). Please see the [migration documentation](https://issues.apache.org/jira/browse/PARQUET-2502) for further details.*</sub>
