### ISSUE TITLE
[R] CRAN packaging checklist for version 18.0.0

### ISSUE THREAD

**Issue by amoeba** [apache/arrow#44496]
### Describe the enhancement requested

# Packaging checklist for CRAN release

For a high-level overview of the release process see the
[Apache Arrow Release Management Guide](https://arrow.apache.org/docs/developers/release.html#post-release-tasks).

cc @jonkeane @thisisnic @amoeba @nealrichardson @assignUser @paleolimbot for coordination on the various tasks to release

## Before the release candidate is cut

- [x] [Create a GitHub issue](https://github.com/apache/arrow/issues/new/) entitled `[R] CRAN packaging checklist for version X.X.X` and copy this checklist to the issue.
- [x] Review deprecated functions to advance their deprecation status, including removing preprocessor directives that no longer apply (search for `ARROW_VERSION_MAJOR` in r/src).
- [x] Evaluate the status of any failing [nightly tests and nightly packaging builds](http://crossbow.voltrondata.com). These checks replicate most of the checks that CRAN runs, so we need them all to be passing or to understand that the failures may (though won't necessarily) result in a rejection from CRAN.
- [x] Check [current CRAN check results](https://cran.rstudio.org/web/checks/check_results_arrow.html)
- [x] Ensure the contents of the README are accurate and up to date.
- [x] Run `urlchecker::url_check()` on the R directory at the release candidate.
  commit. Ignore any errors with badges as they will be removed in the CRAN release branch.
- [x] [Polish NEWS](https://style.tidyverse.org/news.html#news-release) but do **not** update version numbers (this is done automatically later). You can find commits by, for example, `git log --oneline <sha of last release>..HEAD | grep "\[R\]"`
- [x] Run preliminary reverse dependency checks using `archery docker run r-revdepcheck`.
- [ ] For major releases, prepare tweet thread highlighting new features.

Wait for the release candidate to be cut:

## After release candidate has been cut

- [x] Create a CRAN-release branch from the release candidate commit, name the new branch e.g. `maint-X.X.X-r` and push to upstream
  - Created, see https://github.com/apache/arrow/tree/maint-18.0.0-r

## Prepare and check the .tar.gz that will be released to CRAN.

- [x] `git fetch upstream && git checkout release-X.X.X-rcXX && git clean -f -d`
- [x] Run `make build`. This copies Arrow C++ into tools/cpp, prunes some
  unnecessary components, and runs `R CMD build` to generate the source tarball.
  Because this will install the package, you will need to ensure that the version
  of Arrow C++ available to the configure script is the same as the version
  that is vendored into the R package (e.g., you may need to unset `ARROW_HOME`).
- [x] `devtools::check_built("arrow_X.X.X.tar.gz")` locally
- [x] Run reverse dependency checks using `archery docker run r-revdepcheck`.

## Release vote

- [x] Release vote passed!

## Generate R package to submit to CRAN

- [x] If the release candidate commit updated, rebase the CRAN release branch
  on that commit.
- [x] Pick any commits that were made to main since the release commit that
  were needed to fix CRAN-related submission issues identified in the above
  steps.
- [x] Remove badges from README.md
- [x] Run `urlchecker::url_check()` on the R directory
- [x] Create a PR entitled `WIP: [R] Verify CRAN release-10.0.1-rc0`. Add
  a comment `@github-actions crossbow submit --group r` to run all R crossbow
  jobs against the CRAN-specific release branch.
- [x] Run `Rscript tools/update-checksums.R <libarrow version>` to download the checksums for the pre-compiled binaries from the ASF artifactory into the tools directory.
- [x] Regenerate arrow_X.X.X.tar.gz (i.e., `make build`)

## Check binary Arrow C++ distributions specific to the R package

- [x] Upload the .tar.gz to [win-builder](https://win-builder.r-project.org/upload.aspx) (r-devel only)
  and confirm (with Jon, who will automatically receive an email about the results) that the check is clean.
- [x] Upload the .tar.gz to [MacBuilder](https://mac.r-project.org/macbuilder/submit.html)
  and confirm that the check is clean
- [x] Check `install.packages("arrow_X.X.X.tar.gz")` on Ubuntu and ensure that the
  hosted binaries are used
- [x] `devtools::check_built("arrow_X.X.X.tar.gz")` locally one more time (for luck)

## CRAN submission
- [ ] Upload arrow_X.X.X.tar.gz to the
  [CRAN submit page](https://xmpalantir.wu.ac.at/cransubmit/)
- [ ] Confirm the submission email

Wait for CRAN...
- [ ] Accepted!
- [ ] Tag the tip of the CRAN-specific release branch with `r-universe-release`
- [ ] Add a new line to the matrix in the [backwards compatability job](https://github.com/apache/arrow/blob/main/dev/tasks/r/github.linux.arrow.version.back.compat.yml)
- [ ] (patch releases only) Update the package version in `ci/scripts/PKGBUILD`, `dev/tasks/homebrew-formulae/autobrew/apache-arrow.rb`, `r/DESCRIPTION`, and `r/NEWS.md`
- [ ] (CRAN-only releases) Rebuild news page with `pkgdown::build_news()` and submit a PR to the asf-site branch of the docs site with the contents of `arrow/r/docs/news/index.html` replacing the current contents of `arrow-site/docs/r/news/index.html`
- [ ] (CRAN-only releases) Bump the version number in `r/pkgdown/assets/versions.json`, and update this on the [the `asf-site` branch of the docs site](https://github.com/apache/arrow-site) too.
- [ ] Update the packaging checklist template to reflect any new realities of the
  packaging process.
- [ ] Wait for CRAN-hosted binaries on the
  [CRAN package page](https://cran.r-project.org/package=arrow) to reflect the
  new version
- [ ] Tweet!
  - Use Bryce's [script](https://gist.githubusercontent.com/amoeba/4e26c064d1a0d0227cd8c2260cf0072a/raw/bc0d983152bdde4820de9074d4caee9986624bc5/new_contributors.R) for contributor calculation.

### Component(s)

R

**Comment by thisisnic** [comment]
Thanks for kicking this off @amoeba!  I'll make a PR with the NEWS updates

**Comment by amoeba** [comment]
Thanks @thisisnic. I started on a NEWS.md update while working on other releases and so far have this if it helps:

<details>
<summary>18.0.0 NEWS.md content</summary>

```
## New features

* Dictionary columns can now be filtered with the `%in%` operator in dplyr
  pipelines. Previously you would have to cast the dictionary column to a string
  column prior to filtering. (#43440)
* The binding for stringr's `str_sub` function now properly handles negative end
  values instead of returning an empty string. (#43960)

## Minor improvements and fixes

* A performance regression in the binding for dplyr's `summarize` has been
  fixed. This should now be approximately as fast as it was in arrow 16.1.0.
  (#43627)
* The ParquetFileWriter class' WriteTable method can now take a RecordBatch as
  as an argument in addition to a Table. (#42240)
* Add link to ?acero from ?list_compute_functions. (#43509)
```
</details>

**Comment by thisisnic** [comment]
Ah, I just submitted https://github.com/apache/arrow/pull/44520/files - wanna add suggestions there?

**Comment by amoeba** [comment]
Will do! Working on revdep checks now and will look a bit later.

**Comment by amoeba** [comment]
I merged https://github.com/apache/arrow/pull/44520 and cherry-picked it onto `maint-18.0.0-r`. Thanks @thisisnic.

This is waiting on RC vote to be finalized, release to be cut, binaries to be uploaded and then I think we can move forward once that's done. I can start up a social media post draft Monday.

**Comment by thisisnic** [comment]
Thanks very much @amoeba! Are you on BlueSky?  I think we should consider posting there as it appears that a lot of the R community have gone there.

**Comment by amoeba** [comment]
[I am ](https://bsky.app/profile/brycemecum.com), I see you too. I'll plan to post over there this release too. So that means we're covering Twitter, Mastodon, BlueSky (me), and LinkedIn (Jon).

**Comment by nealrichardson** [comment]
About the news, if it's not too late to cherry-pick, I made https://github.com/apache/arrow/pull/44562. NBD if it's too late though.

**Comment by amoeba** [comment]
Not too late. Cherry-picked as 5a5716609107bd5d5a62123d3b1a56b19f252395. I think libarrow binaries for R should be in place so I can kick that test off soon and I'll continue on this once I finish some Arrow release stuff today.

**Comment by amoeba** [comment]
I prepped the submission archive locally following the instructions, submitted to win-builder (r-devel only) and macbuilder (r-release and r-devel), and saved a copy of the archive to my personal Google Drive. We still have two CI failures in https://github.com/apache/arrow/pull/44523 to investigate.

**Comment by thisisnic** [comment]
Looks like we may want to hold off a moment:  https://lists.apache.org/thread/t8k7l2hsbgdt7cszj7hrpjdfpn91n5zb

**Comment by jonkeane** [comment]
I second @thisisnic on holding our release for the 18.0.1. On the positive side, aside from the mirror selection thing that Bryce found in #44523 CI looks good (the devdocs failure is a bit odd, but isn't failing on main, so might be an issue with that running on the release maintenance branch) so hopefully once 18.0.1 is here it'll be a pretty easy submission. 

Thanks for all of the work here @amoeba (and others!)

**Comment by amoeba** [comment]
Holding off sounds good. I'm going to close this issue and note for future-us visiting this issue that we chose not to submit 18.0.0 to CRAN in favor of waiting for the upcoming 18.0.1/18.1.0 release to make our first submission in the 18.x.x series. 

Thanks all for helping with this submission. I'll plan to kickstart the next submission checklist and begin on the items myself, pinging folks as needed.

**Comment by hadley** [comment]
If you're preparing for CRAN release, then it would be awesome if you could squeeze https://github.com/apache/arrow/issues/44674 in.

**Comment by amoeba** [comment]
We can definitely include that. Thanks for filing it.

**Comment by eitsupi** [comment]
Are there any plans to work on the 18.1.0 release?

**Comment by amoeba** [comment]
Yes @eitsupi. Sorry for the low visibility there. The arrow source release for 18.1.0 is almost finished and I'll start the 18.1.0 submission to CRAN in the first half of this week.
