### ISSUE TITLE
[R] CRAN packaging checklist for version 18.1.0

### ISSUE THREAD

**Issue by amoeba** [apache/arrow#44913]
### Describe the enhancement requested

# Packaging checklist for CRAN release

For a high-level overview of the release process see the
[Apache Arrow Release Management Guide](https://arrow.apache.org/docs/developers/release.html#post-release-tasks).

cc @jonkeane @thisisnic @nealrichardson @assignUser @paleolimbot @eitsupi 

## Before the release candidate is cut

- [x] [Create a GitHub issue](https://github.com/apache/arrow/issues/new/) entitled `[R] CRAN packaging checklist for version X.X.X` and copy this checklist to the issue.
- [x] Review deprecated functions to advance their deprecation status, including removing preprocessor directives that no longer apply (search for `ARROW_VERSION_MAJOR` in r/src).
- [x] Evaluate the status of any failing [nightly tests and nightly packaging builds](http://crossbow.voltrondata.com). These checks replicate most of the checks that CRAN runs, so we need them all to be passing or to understand that the failures may (though won't necessarily) result in a rejection from CRAN.
- [x] Check [current CRAN check results](https://cran.rstudio.org/web/checks/check_results_arrow.html)
- [x] Ensure the contents of the README are accurate and up to date.
- [x] Run `urlchecker::url_check()` on the R directory at the release candidate.
  commit. Ignore any errors with badges as they will be removed in the CRAN release branch.
- [x] [Polish NEWS](https://style.tidyverse.org/news.html#news-release) but do **not** update version numbers (this is done automatically later). You can find commits by, for example, `git log --oneline <sha of last release>..HEAD | grep "\[R\]"`
- [x] Run preliminary reverse dependency checks using `archery docker run r-revdepcheck`.
- [x] For major releases, prepare tweet thread highlighting new features.

Wait for the release candidate to be cut:

## After release candidate has been cut

- [x] Create a CRAN-release branch from the release candidate commit, name the new branch e.g. `maint-X.X.X-r` and push to upstream

## Prepare and check the .tar.gz that will be released to CRAN.

- [x] `git fetch upstream && git checkout release-X.X.X-rcXX && git clean -f -d`
- [x] Run `make build`. This copies Arrow C++ into tools/cpp, prunes some
  unnecessary components, and runs `R CMD build` to generate the source tarball.
  Because this will install the package, you will need to ensure that the version
  of Arrow C++ available to the configure script is the same as the version
  that is vendored into the R package (e.g., you may need to unset `ARROW_HOME`).
- [x] `devtools::check_built("arrow_X.X.X.tar.gz")` locally
- [x] Run reverse dependency checks using `archery docker run r-revdepcheck`.

## Release vote

- [x] Release vote passed!

## Generate R package to submit to CRAN

- [x] If the release candidate commit updated, rebase the CRAN release branch
  on that commit.
- [x] Pick any commits that were made to main since the release commit that
  were needed to fix CRAN-related submission issues identified in the above
  steps.
- [x] Remove badges from README.md
- [x] Run `urlchecker::url_check()` on the R directory
- [x] Create a PR entitled `WIP: [R] Verify CRAN release-10.0.1-rc0`. Add
  a comment `@github-actions crossbow submit --group r` to run all R crossbow
  jobs against the CRAN-specific release branch.
- [x] Run `Rscript tools/update-checksums.R <libarrow version>` to download the checksums for the pre-compiled binaries from the ASF artifactory into the tools directory.
- [x] Regenerate arrow_X.X.X.tar.gz (i.e., `make build`)

## Check binary Arrow C++ distributions specific to the R package

- [x] Upload the .tar.gz to [win-builder](https://win-builder.r-project.org/upload.aspx) (r-devel only)
  and confirm (with Jon, who will automatically receive an email about the results) that the check is clean.
- [x] Upload the .tar.gz to [MacBuilder](https://mac.r-project.org/macbuilder/submit.html)
  and confirm that the check is clean
- [x] Check `install.packages("arrow_X.X.X.tar.gz")` on Ubuntu and ensure that the
  hosted binaries are used
- [x] `devtools::check_built("arrow_X.X.X.tar.gz")` locally one more time (for luck)

## CRAN submission
- [x] Upload arrow_X.X.X.tar.gz to the
  [CRAN submit page](https://xmpalantir.wu.ac.at/cransubmit/)
- [x] Confirm the submission email

Wait for CRAN...
- [x] Accepted!
- [x] Tag the tip of the CRAN-specific release branch with `r-universe-release`
- [ ] Add a new line to the matrix in the [backwards compatability job](https://github.com/apache/arrow/blob/main/dev/tasks/r/github.linux.arrow.version.back.compat.yml)
- [x] (patch releases only) Update the package version in `ci/scripts/PKGBUILD`, `dev/tasks/homebrew-formulae/autobrew/apache-arrow.rb`, `r/DESCRIPTION`, and `r/NEWS.md`
- [x] (CRAN-only releases) Rebuild news page with `pkgdown::build_news()` and submit a PR to the asf-site branch of the docs site with the contents of `arrow/r/docs/news/index.html` replacing the current contents of `arrow-site/docs/r/news/index.html`
- [x] (CRAN-only releases) Bump the version number in `r/pkgdown/assets/versions.json`, and update this on the [the `asf-site` branch of the docs site](https://github.com/apache/arrow-site) too.
- [x] Update the packaging checklist template to reflect any new realities of the
  packaging process.
- [x] Wait for CRAN-hosted binaries on the
  [CRAN package page](https://cran.r-project.org/package=arrow) to reflect the
  new version
- [x] Tweet!
  - Use Bryce's [script](https://gist.githubusercontent.com/amoeba/4e26c064d1a0d0227cd8c2260cf0072a/raw/bc0d983152bdde4820de9074d4caee9986624bc5/new_contributors.R) for contributor calculation.

### Component(s)

R

**Comment by assignUser** [comment]
Awesome, thanks!

**Comment by amoeba** [comment]
There are a few failures over in the verification PR that need investigating (test-r-devdocs, test-r-rhub-debian-gcc-devel-lto-latest, r-recheck-most). I'll plan to work on them later today/tomorrow.

**Comment by amoeba** [comment]
I looked into the two crossbow job failures and neither looked simple to diagnose and fix. @assignUser can you have a look? It's also not clear to me whether these two failures should hold up submitting to CRAN.

The recheck job above fails but it looks like that's fine since the failure is just because the recheck result for a couple of packages changed from 17.x to 18.x.

**Comment by jonkeane** [comment]
> Strangely, the submission to release reports itself as r-devel-macosx-arm64 whereas the submission to devel reports itself as r-oldrel-macosx-arm64. Is that backwards?

Oh that is very strange! And even stranger the _version numbers_ are the right way around 4.4 for release and 4.5 for devel. And in the first few lines of the check log for devel there is `using R Under development (unstable) (2024-04-24 r86482)` too. So weird!

> Is this a transient mac builder issue?

Yeah, that looks like something is up with the environment there — you could try again and see if it _just works_?

Ideally r-devel passes mac builder, but this kind of failure looks much more like a macbuilder env issue than an arrow-the-package issue, so I would be ok submitting to CRAN still even if this hasn't passed. Some reasoning behind that: we haven't changed our `DESCRIPTION` file or dependencies, which is why something like that would change _because of us_.

**Comment by jonkeane** [comment]
I just submitted the tar to CRAN 🤞 *Thank you* @amoeba for all of your help on this, I couldn't have done it without you

**Comment by jonkeane** [comment]
> package arrow_18.1.0.tar.gz is on its way to CRAN

And we are already seeing checks roll into https://cran.r-project.org/web/checks/check_results_arrow.html

**Comment by assignUser** [comment]
a. wow css (colors) on cran
b. what's up with the non-informative error output? That looks like testthat.r echoed?

**Comment by nealrichardson** [comment]
> a. wow css (colors) on cran
> 

😂

> b. what's up with the non-informative error output? That looks like testthat.r echoed?

I would guess that means something crashed or exited unexpectedly somewhere. Maybe even an oom-kill? Something where stdout isn't informative. 

IIRC macOS checks will automatically rerun so let's see if it happens again?

**Comment by assignUser** [comment]
> IIRC macOS checks will automatically rerun so let's see if it happens again?

It did not :tada:

**Comment by amoeba** [comment]
Hey all, it looks like the CRAN binaries have been built (with the exception of windows `r-devel`) so I think we can post to socials. I've started [a Google Doc](https://docs.google.com/document/d/1QIwrcCMVfwMwgDliRr-TaVU-irlsLOGES_-qWx4fJe0/edit?usp=sharing). Due to the small changeset in this release, I decided not to do a long tweet thread with screenshots. However, I could be convinced to hype this up more if anyone feels differently. I'll do a final copy-edit before posting anywhere but please have a look. I'll plan to post to Twitter, Mastodon, and Blue Sky.

I've also submitted a [PR to sync the docs](https://github.com/apache/arrow-site/pull/568) if anyone wants to do a quick review.

Once those two things (social posts, website PR) are done, I think we can close this release out.

**Comment by amoeba** [comment]
@jonkeane do you want to have a look at the [social media google doc](https://docs.google.com/document/d/1QIwrcCMVfwMwgDliRr-TaVU-irlsLOGES_-qWx4fJe0/edit?pli=1&tab=t.0)? I'll plan to post regardless but a review would be great.

**Comment by nealrichardson** [comment]
Thank you for wrangling this. I made a couple of suggestions in the doc. Jon is on vacation now so I'm not sure they will be available to respond (or skeet).

**Comment by amoeba** [comment]
Thanks for the edits on the social media doc, it's much appreciated @nealrichardson. Shoulda pinged you in the first place. 

I'll schedule my posts to go out tomorrow.

**Comment by assignUser** [comment]
fyi: https://github.com/apache/arrow/issues/44995

**Comment by amoeba** [comment]
Closing this out as the checklist is complete. Thanks all for the help with the release tasks.
